name: task_manager
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  
  # State management
  provider: ^6.1.2

  # Hive (database offline)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Firebase
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.15.0

  # Utilities
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Code generators
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
