// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3X-V885yjOR7Ao-W5Gz8mrEYkWiIbE_I',
    appId: '1:291381323204:web:9340ec310bda7303943091',
    messagingSenderId: '291381323204',
    projectId: 'hieu-taskmanager',
    authDomain: 'hieu-taskmanager.firebaseapp.com',
    storageBucket: 'hieu-taskmanager.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-wzRzRIygZfH-r-WMLZa45BG06BoJD3U',
    appId: '1:291381323204:android:0c4c277c75acca96943091',
    messagingSenderId: '291381323204',
    projectId: 'hieu-taskmanager',
    storageBucket: 'hieu-taskmanager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrLRPSMF5And_yO9r7NdlqW-I7XQluRmc',
    appId: '1:291381323204:ios:1a02b4c18abe9316943091',
    messagingSenderId: '291381323204',
    projectId: 'hieu-taskmanager',
    storageBucket: 'hieu-taskmanager.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrLRPSMF5And_yO9r7NdlqW-I7XQluRmc',
    appId: '1:291381323204:ios:1a02b4c18abe9316943091',
    messagingSenderId: '291381323204',
    projectId: 'hieu-taskmanager',
    storageBucket: 'hieu-taskmanager.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3X-V885yjOR7Ao-W5Gz8mrEYkWiIbE_I',
    appId: '1:291381323204:web:e8b2cee48526d12f943091',
    messagingSenderId: '291381323204',
    projectId: 'hieu-taskmanager',
    authDomain: 'hieu-taskmanager.firebaseapp.com',
    storageBucket: 'hieu-taskmanager.firebasestorage.app',
  );
}
