// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATXLYmCBICjbaAonkTi52WJmAO2rhkca8',
    appId: '1:392134374842:web:4ad596e69c35f915d7d983',
    messagingSenderId: '392134374842',
    projectId: 'da-task-dbe5b',
    authDomain: 'da-task-dbe5b.firebaseapp.com',
    storageBucket: 'da-task-dbe5b.firebasestorage.app',
    measurementId: 'G-SDX0Y1N7LG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOXlAlmDzpUTKC3gFLNLI7wjLw43jlUyQ',
    appId: '1:392134374842:android:530a65ec6cff19d8d7d983',
    messagingSenderId: '392134374842',
    projectId: 'da-task-dbe5b',
    storageBucket: 'da-task-dbe5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQIf81tmql4VS78RDTRUJwbtrDnkkwbD0',
    appId: '1:392134374842:ios:b1a97501b83d73fdd7d983',
    messagingSenderId: '392134374842',
    projectId: 'da-task-dbe5b',
    storageBucket: 'da-task-dbe5b.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQIf81tmql4VS78RDTRUJwbtrDnkkwbD0',
    appId: '1:392134374842:ios:b1a97501b83d73fdd7d983',
    messagingSenderId: '392134374842',
    projectId: 'da-task-dbe5b',
    storageBucket: 'da-task-dbe5b.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATXLYmCBICjbaAonkTi52WJmAO2rhkca8',
    appId: '1:392134374842:web:8bff04163d9f483dd7d983',
    messagingSenderId: '392134374842',
    projectId: 'da-task-dbe5b',
    authDomain: 'da-task-dbe5b.firebaseapp.com',
    storageBucket: 'da-task-dbe5b.firebasestorage.app',
    measurementId: 'G-MD8CQ9DFVF',
  );
}
